lang: 1
id: US
label: "American ğŸ‡ºğŸ‡¸"
description: Amercan english accent descriptiion...
benchmark: True
weight: 0.35
samples: sample.file
---
lang: 2
id: BR
label: "British ğŸ‡¬ğŸ‡§"
description: British english accent descriptiion...
benchmark: True
weight: 0.65
samples: sample.file
---
lang: 3
id: IN
label: "Indian ğŸ‡®ğŸ‡³"
description: Indian english accent descriptiion...
benchmark: False
samples: sample.file
---
lang: 4
id: RU
label: "Russian ğŸ»"
description: Russian english accent descriptiion...
benchmark: False
samples: sample.file
---
lang: 5
id: SC
label: "Scottish ğŸ´ó §ó ¢ó ³ó £ó ´ó ¿"
description: Scottish english accent descriptiion...
benchmark: False
samples: sample.file
---
lang: 6
id: SP
label: "Spanish ğŸ‡ªğŸ‡¸"
description: Spanish english accent descriptiion...
benchmark: False
samples: sample.file